server:
  port: 9192

spring:
  datasource:
    username: root
    password:
    url: jdbc:mysql://localhost:3306/lakeSide_hotel_db
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      format_sql: true
  servlet:
    multipart:
    max-file-size: 8MB
    max-request-size: 8MB
    file-size-threshold: 5KB

    security:
      jwt:
        secret-key: 36763979244226452948404D635166546A576D5A7134743777217A25432A462D
        expire-length: 3600000
